- hosts: 'workers, masters'
  become: yes
  
  tasks:
    - name: verify the hosts file by run 'whoami' command
      shell: whoami
      register: result

    - debug:
        var: result
        # verbosity: 2
